FROM ci-dev-docker.art.ocp.csvw.com/library/nginx-118:latest
ARG URL_PATH
ENV $URL_PATH URL_PATH
RUN echo '环境变量URL：' + $URL_PATH
COPY ./dist/ /usr/share/nginx/html/
COPY ./env.sh /usr/share/
COPY ./nginx.conf /etc/nginx/nginx.conf
RUN chmod +x /usr/share/env.sh  \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && chmod 777 -R /etc/nginx \
    && chmod 777 -R /usr/share/nginx \
    && mkdir -p /var/cache/nginx \
    && chmod 777 /var/cache/nginx \
    && chmod 777 /var/run
CMD /usr/share/env.sh && nginx -g 'daemon off;'
