FROM ci-dev-docker.art.ocp.csvw.com/library/nginx-118:latest
USER root
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
COPY ./dist/ /usr/share/nginx/html/
COPY ./nginx.conf /etc/nginx/nginx.conf
CMD nginx -g 'daemon off;'
