export const rawMaterialSearch = [
  {
    type: 'select',
    props: 'a',
    options: [],
    labelLanguageKey: 'PLGLZS.LEIBIE',
    label: '类别',
    placeholderLanguageKey: 'PLGLZS.QINGXUANZELEIBIE',
    placeholder: '请选择类别',
  },
  {
    type: 'select',
    props: 'b',
    options: [],
    labelLanguageKey: 'PLGLZS.GUIGEPAIHAO',
    label: '规格/牌号',
    placeholderLanguageKey: 'PLGLZS.QINGXUANZEPAIHAO',
    placeholder: '请选择牌号',
  },
  {
    type: 'select',
    props: 'c',
    options: [],
    labelLanguageKey: 'PLGLZS.QUYU',
    label: '区域',
    placeholderLanguageKey: 'PLGLZS.QINGXUANZEQUYU',
    placeholder: '请选择区域',
  },
  {
    type: 'dateMonth',
    props: 'd',
    labelLanguageKey: 'PLGLZS.SHIJIANFANWEI',
    label: '时间范围',
  },
  {
    type: 'input',
    props: 'e',
    labelLanguageKey: 'PLGLZS.SHUJULAIYUAN',
    label: '数据来源',
  },
];

export const manpowerSearch = [
  {
    type: 'select',
    props: 'a',
    options: [],
    labelLanguageKey: 'PLGLZS.GONGZHONG',
    label: '工种',
    placeholderLanguageKey: 'PLGLZS.QINGXUANGONGZHONG',
    placeholder: '请选择工种',
  },
  {
    type: 'select',
    props: 'b',
    options: [],
    labelLanguageKey: 'PLGLZS.QUYU',
    label: '区域',
    placeholderLanguageKey: 'PLGLZS.QINGXUANZEQUYU',
    placeholder: '请选择区域',
  },
  {
    type: 'dateMonth',
    props: 'c',
    labelLanguageKey: 'PLGLZS.SHIJIANFANWEI',
    label: '时间范围',
  },
  {
    type: 'input',
    props: 'd',
    labelLanguageKey: 'PLGLZS.SHUJULAIYUAN',
    label: '数据来源',
  },
];

export const energySearch = [
  {
    type: 'select',
    props: 'a',
    options: [],
    labelLanguageKey: 'PLGLZS.CHANPINMINGCHENG',
    label: '产品名称',
    placeholderLanguageKey: 'PLGLZS.QINGXUANZECHANPINMINGCHENG',
    placeholder: '请选择产品名称',
  },
  {
    type: 'select',
    props: 'b',
    options: [],
    labelLanguageKey: 'PLGLZS.SHICHANGMINGCHENG',
    label: '市场名称',
    placeholderLanguageKey: 'PLGLZS.QINGXUANZESHICHANGMINGCHENG',
    placeholder: '请选择市场名称',
  },
  {
    type: 'select',
    props: 'c',
    options: [],
    labelLanguageKey: 'PLGLZS.JIAGELEIXING',
    label: '价格类型',
    placeholderLanguageKey: 'PLGLZS.QINGXUANZEJIAGELEIXING',
    placeholder: '请选择价格类型',
  },
  {
    type: 'select',
    props: 'd',
    options: [],
    labelLanguageKey: 'PLGLZS.DANWEI',
    label: '单位',
    placeholderLanguageKey: 'PLGLZS.QINGXUANZEDANWEI',
    placeholder: '请选择单位',
  },
  {
    type: 'dateMonth',
    props: 'e',
    labelLanguageKey: 'PLGLZS.SHIJIANFANWEI',
    label: '时间范围',
  },
  {
    type: 'input',
    props: 'f',
    labelLanguageKey: 'PLGLZS.SHUJULAIYUAN',
    label: '数据来源',
  },
]
