/*
 * @Author: your name
 * @Date: 2021-02-19 14:29:21
 * @LastEditTime: 2021-10-27 13:14:01
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: \rise\src\views\ui\components\data.js
 */

 export const tabelTile = [
   {
     key:'a',
     name:'headerOne'
   },
   {
    key:'b',
    name:'headerTow'
  },
  {
    key:'c',
    name:'headerThree'
  },
  {
    key:'d',
    name:'headerFour'
  },
  {
    key:'e',
    name:'headerFive'
  },
  {
    key:'f',
    name:'headerSix'
  },
  {
    key:'g',
    name:'headerSeven'
  }
 ]


 export const excelExport = [
   {
     name:'这是一个菜单',
     child:[
       {name:'这是一个子菜单',
        child:[
          {name:'这是一个控件名字'},
          {name:'这是一个控件名字'},
          {name:'这是一个控件名字'},
          {name:'这是一个控件名字'},
          {name:'这是一个控件名字'},
          {name:'这是一个控件名字'},
          {name:'这是一个控件名字'},
          {name:'这是一个控件名字'},
          {name:'这是一个控件名字'},
          {name:'这是一个控件名字'},
          {name:'这是一个控件名字'},
        ]
       },
     ]
   },
   {
    name:'这是一个菜单',
    child:[
      {name:'这是一个子菜单',
       child:[
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
       ]
      },
    ]
  },
  {
    name:'这是一个菜单',
    child:[
      {name:'这是一个子菜单',
       child:[
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
       ]
      },
    ]
  },
  {
    name:'这是一个菜单',
    child:[
      {name:'这是一个子菜单',
       child:[
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
         {name:'这是一个控件名字'},
       ]
      },
    ]
  },
  {
    name:'这是一个菜单',
    child:[
      {name:'这是一个控件名字'},
      {name:'这是一个控件名字'},
      {name:'这是一个控件名字'},
      {name:'这是一个控件名字'},
      {name:'这是一个控件名字'},
      {name:'这是一个控件名字'},
      {name:'这是一个控件名字'},
      {name:'这是一个控件名字'},
      {name:'这是一个控件名字'},
      {name:'这是一个控件名字'},
      {name:'这是一个控件名字'},
    ]
  },
  {
    name:'这是一个菜单',
    child:[
      { name:'子菜单之一',
        child:[
          {name:'子菜单之一',child:[{name:'控件名字'}]}
        ]
      }
    ]
  },
 ]