
export const tabRouterList = [
	{
    value: 1,
    name: '零件目标价',
    message: 0,
    url: '/targetpriceandscore/financialtargetprice/maintenance',
    activePath: 'financialtargetprice',
    key: 'LINGJIANMUBIAOJIA',
    permissionKey: 'FINANCIALMANAGE_MENU_PARTTARGETPRICE',
    permissionName: '零件目标价',
    group: 1,
  },
  {
    value: 2,
    name: '模具目标价',
    message: 0,
    url: '/targetpriceandscore/modeltargetprice/signin',
    activePath: 'modeltargetprice',
    key: 'MOJUMUBIAOJIA',
    permissionKey: 'FINANCIALMANAGE_MENU_MODELTARGETPRICE',
    permissionName: '模具目标价',
    group: 2,
  },
  {
    value: 3,
    name: '零件经销价',
    message: 0,
    url: '/targetpriceandscore/productionCapacity',
    activePath: 'productionCapacity',
    key: 'partsprocure.LJJXJ',
    permissionKey: 'FINANCIALMANAGE_MENU_MODELTARGETPRICE',
    // permissionKey: 'FINANCIALMANAGE_MENU_PRODUCTIONCAPACITY',
    permissionName: '零件经销价',
    group: 3,
  },
]
export const tableTitledistribution = [
    {
      props: 'partNum',
      name: '零件号',
      key: 'partsprocure.PARTSPROCUREPARTNUMBER',
      align: 'center',
      tooltip: true,
      width:150,
    }, {
      props: 'partNameZh',
      name: '零件名称',
      key: 'LK_LINGJIANMINGCHENG',
      align: 'center',
      tooltip: true,
      width:150,
    }, {
      props: 'supplierShortNameZh',
      name: '散件供应商',
      key: 'SANJIANGONGYINGSHANG',
      align: 'center',
      tooltip: true,
      width:150,
    },{
      props: 'factoryName',
      name: '采购工厂',
      key: 'LK_CAIGOUGONGCHANG',
      align: 'center',
      tooltip: true,
    },{
      props: 'price',
      name: '经销价',
      key: 'JINGXIAOJIA',
      align: 'center',
      tooltip: true,
    },{
      props: 'createDate',
      name: '创建时间',
      key: 'LK_CHUANGJIANSHIJIAN',
      align: 'center',
      tooltip: true,
    },{
      props: 'startDate',
      name: '价格开始日期',
      key: 'JIAGEKAISHIRIQI',
      align: 'center',
      tooltip: true,
    },{
      props: 'endDate',
      name: '价格结束日期',
      key: 'JIAGEJIESHURIQI',
      align: 'center',
      tooltip: true,
    },{
      props: 'measureUnit',
      name: '单位',
      key: 'LK_IDANWEI',
      align: 'center',
      tooltip: true,
    },{
      props: 'currency',
      name: '货币',
      key: 'LK_HUOBI',
      align: 'center',
      tooltip: true,
    },{
      props: 'exchangeRate',
      name: '汇率',
      key: 'LK_HUILV',
      align: 'center',
      tooltip: true,
    },{
      props: 'remark',
      name: '备注',
      key: 'BEIZHU',
      align: 'center',
      tooltip: true,
    },
  ]
