// MTZ-规则清单
export const ruleTableTitle = [//决策资料规则清单暂用
  { 
      props: 'yearCw',
      name: 'Year CW',
      key: 'Year CW',
      // overlap:true,
      // overlapbottom:"Rule No.",
      minWidth:80
  },
  {
      props: 'ttMtzAppId',
      name: 'Nomination No.',
      key: 'Nomination No.',
      // overlap:true,
      // overlapbottom:"MTZ group",
      minWidth:103
  },
  { 
      props: 'ruleNo', 
      name: 'Rule No.', 
      key: 'Rule No.',
      // overlap:true,
      // overlapbottom:"Carline",
      minWidth:60,
  },
  {
      props: 'materialGroupName',
      name: 'MTZ Materiral Group',
      key: 'MTZ Materiral Group',
      overlap:true,
      overlapbottom:"Group",
      minWidth:110,
  },
  {
      props: 'carline',
      name: 'Carline',
      key: 'Carline',
      // overlap:true,
      // overlapbottom:"Material Code",
      minWidth:80,
  },
  {
      props: 'supplierName',
      name: 'Supplier',
      key: 'Supplier',
      // overlap:true,
      // overlapbottom:"Material Division",
      minWidth:100,
  },
  { 
      props: 'materialName', 
      name: 'Material', 
      key: 'Material',
      // overlap:true,
      // overlapbottom:"Base price",
      minWidth:70,
  },
  {
      props: 'materialCode',
      name: 'Material Code',
      key: 'Material Code',
      overlap:true,
      overlapbottom:"Code",
      minWidth:115,
  },
  { 
      props: 'price', 
      name: 'Price', 
      key: 'Price',
      // overlap:true,
      // overlapbottom:"Currency",
      minWidth:70,
  },
  { 
      props: 'priceMeasureUnit', 
      name: 'Price Unit', 
      key: 'Price Unit',
      overlap:true,
      overlapbottom:"Unit",
      minWidth:105,
  },
  {
      props: 'tcCurrence',
      name: 'Currency',
      key: 'Currency',
      // overlap:true,
      // overlapbottom:"Market",
      minWidth:95,
  },
  {
      props: 'tcExchangeRate',
      name: 'Exchange Rate',
      key: 'Exchange Rate',
      overlap:true,
      overlapbottom:"Rate",
      minWidth:80,
  },
  { 
      props: 'sourceType', 
      name: 'Price Market', 
      key: 'Price Market',
      overlap:true,
      overlapbottom:"Market",
      minWidth:90,
  },
  { 
      props: 'compensationPeriod', 
      name: 'Period', 
      key: 'Period',
      // overlap:true,
      // overlapbottom:"Valid To",
      minWidth:90,
  },
  { 
      props: 'startDate', 
      name: 'Valid From', 
      key: 'Valid From',
      // overlap:true,
      // overlapbottom:"Valid To",
      minWidth:90,
  },
  { 
      props: 'endDate', 
      name: 'Valid To', 
      key: 'Valid To',
      // overlap:true,
      // overlapbottom:"Valid To",
      minWidth:90,
  },
]

// MTZ-零件清单
export const partTableTitle = [
  { 
      props: 'yearCw',
      name: 'Year CW',
      key: 'Year CW',
      // overlap:true,
      // overlapbottom:"Rule No.",
      minWidth:80
  },
  {
      props: 'ttMtzAppId',
      name: 'Nomination No.',
      key: 'Nomination No.',
      // overlap:true,
      // overlapbottom:"MTZ group",
      minWidth:103
  },
  { 
      props: 'carline', 
      name: 'Part No.', 
      key: 'Part_No.',
      // overlap:true,
      // overlapbottom:"Carline",
      minWidth:60,
  },
  {
    props: 'partName',
    name: 'Part Name',
    key: 'Part_Name',
  //   overlap:true,
  //   overlapbottom:"Material Code",
    minWidth: 80,
  },
  { 
      props: 'supplierName', 
      name: 'Supplier',
      key: 'Supplier',
      // overlap:true,
      // overlapbottom:"Material",
      minWidth: 60,
  },
  { 
      props: 'materialName', 
      name: 'Material', 
      key: 'Material',
      // overlap:true,
      // overlapbottom:"Supplier",
      minWidth: 60,
  },
  {
      props: 'materialCode', 
      name: 'Material Code', 
      key: 'Material Code',
      overlap:true,
      overlapbottom:"Code",
       minWidth: 70,
  },
  {
      props: 'dosage',
      name: 'Usage',
      key: 'Usage',
      // overlap:true,
      // overlapbottom:"Base price Unit",
      minWidth: 80,
  },
  { 
      props: 'dosageMeasureUnit', 
      name: 'Usage Unit', 
      key: 'Usage Unit',
      overlap:true,
      overlapbottom:"Unit",
      minWidth: 50,
  },
  {
      props: 'tcCurrence',
      name: 'Currency',
      key: 'Currency',
      // overlap:true,
      // overlapbottom:"Part Unit",
      minWidth: 80,
  },
  { 
      props: 'tcExchangeRate', 
      name: 'Exchange Rate', 
      key: 'Exchange Rate',
      overlap:true,
      overlapbottom:"Rate",
      minWidth: 60,
  },
  {
      props: 'sourceType',
      name: 'Price Market',
      key: 'Price Market',
      overlap:true,
      overlapbottom:"Market",
      minWidth: 80,
  },
  {
      props: 'compensationPeriod',
      name: 'Period',
      key: 'Period',
      // overlap:true,
      // overlapbottom:"Market",
      minWidth: 70,
  },
  { 
      props: 'startDate', 
      name: 'Valid From',
      key: 'Valid From',
      // overlap:true,
      // overlapbottom:"Valid From",
      minWidth: 75,
  },
  { 
      props: 'endDate', 
      name: 'Valid To', 
      key: 'Valid To',
      // overlap:true,
      // overlapbottom:"Valid To",
      minWidth: 75,
  },
]