// const authList = [
//   'ACHIEVEMENTMGT_LIST_NEWADD',// 新增
//   'ACHIEVEMENTMGT_LIST_INVALID',// 失效
//   'ACHIEVEMENTMGT_AMOUNT_ADJUSTMENT',// 业绩金额调整
//   'ACHIEVEMENTMGT_LIST_YIEIDMANAGE',// 产量管理
//   'ACHIEVEMENTMGT_LIST_TARGETMANAGE',// 年度目标管理
//   'ACHIEVEMENTMGT_LIST_CONFIRM',// 发起确认
//   'ANNUALTARGET_PAGE_NOTICE',// 通知科室
//   'ANNUALTARGET_PAGE_SAVEDATA',// 确认
//   'ACHIEVEMENTMGT_LIST_REFRESH',// 刷新
//   'ACHIEVEMENT_DETAIL_PAGE_BATCHEDIT',// 批量编辑
//   'ACHIEVEMENT_DETAIL_PAGE_EDIT',// 编辑
//   'ACHIEVEMENT_DETAIL_PAGE_CONFIRM',// 确认
//   'ACHIEVEMENT_DETAIL_PAGE_REASSIGNMENT',// 转派
//   'ACHIEVEMENT_DETAIL_PAGE_EXPORT',// 导出
//   'ACHIEVEMENT_DETAIL_PAGE_SAVE',// 保存
//   'ACHIEVEMENT_TRACK_PAGE_EDIT',// 编辑
//   'ACHIEVEMENT_TRACK_PAGE_SAVE',// 保存
//   'ACHIEVEMENT_TRACK_PAGE_EXPORT',// 导出
//   'OUTPUT_MANAGEMENT_PAGE_DOWNLOAD',// 下载模板
//   'OUTPUT_MANAGEMENT_PAGE_UPLOAD',// 上传产量
//   'OUTPUT_MANAGEMENT_PAGE_DELETE',// 删除
//   'OUTPUT_MANAGEMENT_PAGE_RETURNSTEP',// 返回上级
//   'ACHIEVEMENTMGT_SPARE_ANNUAL_TATGET',// 配附件
//   'ACHIEVEMENTMGT_TABLE_TEMPLATE_DOWN',// 配附件
//   'ACHIEVEMENTMGT_SPARE_CONFIRM',// 配附件
//   'ACHIEVEMENTMGT_SPARE_TRACK_DOWN',// 配附件导出
//   'ACHIEVEMENTMGT_SPARE_BASETABLE_DOWN',// 配附件导出
//   'ACHIEVEMENTMGT_SPARE_BASETABLE_TRANSFER',// 转派
//   'ACHIEVEMENTMGT_SPARE_BASETABLE_CONFIRM',// 确认
// ]
const isAuth = (authKeyData,authKey) => {
  const authList = []
  for (var key in authKeyData) {
    authList.push(key)
  }
  const status = authList.some((key => key == authKey))
  return status
}
export default isAuth